# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FT68lYKKCWkQkeqGXI9unxEO8BFWyvFu
"""

from keras.models import Sequential
from keras.layers import Dense, MaxPooling2D, Flatten, Conv2D, Dropout
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import matplotlib.pyplot as plt
#tien xu li du lieu
#thiet lap duong dan
train_dir="/content/drive/MyDrive/dataset tiền"

#Kich thuoc anh va lo
img_width,  img_height= 128, 128
batch_size = 32

#tăng cường dữ liệu dành cho huấn luyện
train_datagen = ImageDataGenerator(
    rescale=1.0/225,   #Normalize pixel values
    rotation_range=30,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=False,
    fill_mode="nearest"
)

train_generator=train_datagen.flow_from_directory(
    train_dir,
    target_size=(img_width, img_height),
    batch_size=batch_size,
    class_mode='categorical'
)

# XÂY DỰNG MÔ HÌNH CNN
model = Sequential([
    Conv2D(32, (3,3), activation="relu", input_shape=(img_width, img_height, 3)),
    MaxPooling2D(2,2),
    Conv2D(64, (3,3), activation="relu"),
    MaxPooling2D(2,2),
    Conv2D(128, (3,3), activation="relu"),
    MaxPooling2D(2,2),
    Flatten(),
    Dense(128, activation="relu"),
    Dropout(0.5),
    Dense(5, activation="softmax")
])

model.compile(optimizer="adam",
              loss="categorical_crossentropy",
              metrics=["accuracy"])
# # Tóm tắt cấu hình của mô hình
model.summary()

#Huấn luyện mô hình CNN
epochs=50
history=model.fit(train_generator,epochs=epochs)

#Đánh giá kết quả mô hình
plt.plot(history.history['accuracy'], label="kết quả huấn luyện")
# If you want to plot validation accuracy, you need to provide validation_data to model.fit()
# plt.plot(history.history['val_accuracy'], label="Độ chính xác xác thực")
plt.xlabel("số lần học")
plt.ylabel("Độ chính xác") # Corrected: removed parentheses around the string
plt.legend()
plt.show()

from keras.utils import load_img
import numpy as np
import matplotlib.pyplot as plt

path = "/content/images (38).jpg"

img_width, img_height = 128, 128
img = load_img(path, target_size=(img_width, img_height))
plt.imshow(img)
plt.show()

img = np.array(img)
img = img / 255.0
img = img.reshape(1, img_width, img_height, 3)
prediction = np.argmax(model.predict(img))


class_labels = {v: k for k, v in train_generator.class_indices.items()}
person_name = class_labels[prediction]
print(f"Tờ tiền trị giá: {person_name}")

